### ISSUE TITLE
Some automated tests fail

### ISSUE THREAD

**Issue by jyrkive** [avoinministerio/avoinministerio#143]
Finished in 9.98 seconds
111 examples, 4 failures, 9 pending

Failed examples:

rspec ./spec/controllers/ideas_controller_spec.rb:15 # IdeasController#show should show an idea
rspec ./spec/controllers/ideas_controller_spec.rb:22 # IdeasController#show should show an idea with slugged url
rspec ./spec/controllers/ideas_controller_spec.rb:42 # IdeasController#show logged in user should show the voting form if not already voted
rspec ./spec/controllers/ideas_controller_spec.rb:48 # IdeasController#show logged in user should show an option to change opinion if already voted

That happens on my fork's master (which should be exactly identical with your master) when I run "bundle exec rake db:migrate db:test:prepare" followed by "bundle exec rake spec".

**Comment by datakurre** [comment]
Quite the same with master (by just following the README).

```
Finished in 95.28 seconds
111 examples, 5 failures, 9 pending

Failed examples:

rspec ./spec/controllers/pages_controller_spec.rb:23 # PagesController#home drafts section should calculate vote counts for a draft
rspec ./spec/controllers/ideas_controller_spec.rb:15 # IdeasController#show should show an idea
rspec ./spec/controllers/ideas_controller_spec.rb:22 # IdeasController#show should show an idea with slugged url
rspec ./spec/controllers/ideas_controller_spec.rb:42 # IdeasController#show logged in user should show the voting form if not already voted
rspec ./spec/controllers/ideas_controller_spec.rb:48 # IdeasController#show logged in user should show an option to change opinion if already voted
```

**Comment by jyrkive** [comment]
It's even worse now. Here is a sample of test output:

```
..[0, 0, false]
.[0, 0, false]
.*..[0, 0, false]
[0, 0, false]
.[0, 0, false]
[0, 0, false]
.[0, 0, false]
[0, 0, false]
.[0, 0, false]
[0, 0, false]
.[0, 0, false]
[0, 0, false]
.[0, 0, false]
```

Something keeps outputting the text [0, 0, false] during the tests. In addition, time required to run the tests has increased from ten seconds to two minutes.

**Comment by jyrkive** [comment]
**I found the cause for the [0, 0, false] output!!!** :) I'll create a pull request to fix it ASAP. (Unfortunately the slowness and failing tests are still there.)

**Comment by jyrkive** [comment]
[Pull request 160](https://github.com/avoinministerio/avoinministerio/pull/160) created.

**Comment by jyrkive** [comment]
[This has been fixed](https://github.com/avoinministerio/avoinministerio/commit/2ba2f79527105248b84c531fe841d48fdbad05a4). :)
