### ISSUE TITLE
See my own votes

### ISSUE THREAD

**Issue by nikcorg** [avoinministerio/avoinministerio#151]
As far as I can find, it is not possible to see my own votes, unless I manually keep a list of bookmarks to the issues I vote on.

Adding a page that would list the issues I have voted on should be quite straight forward. Unfortunately, I'm not at all familiar with Ruby and thus unable to provide a pull request.

On this same page, it could also be possible to display recent activities on the issues I've voted on. (Amendments, comments etc.)

**Comment by naleksi** [comment]
This is definitely an interesting feature, and one that we're going to implement. At the moment there's no reliable road map to lean on to provide some estimate of the timeframe. There are many things that have a priority at a moment. Snappy full text search, various bug fixes, and most importantly electronically signed support statements. After those have been approved by the officials we will strive to add tags and duplicates, some automated emails and finally user profiles and beginnings of social features. Thanks for the suggestion! It would be a good candidate for Devaamo Summit on next weekend.

I'll not close the issue yet. In general we track the feature requests in Trello and promote kehitysehdotukset@avoinministerio.fi to submit them, but let's have this one here for the moment.

**Comment by nikcorg** [comment]
Closing, as this project is quite obviously dead.
