### ISSUE TITLE
henkilorekisteriseloste is incorrect with regards to Eu/Eta

### ISSUE THREAD

**Issue by betelgeuse** [avoinministerio/avoinministerio#203]
```
;; ANSWER SECTION:
www.avoinministerio.fi. 3019    IN  CNAME   appid3039927herokucom-1547551321.us-east-1.elb.amazonaws.com.
```

As the code is hosted on Heroku it is not correct to say that personal information will not be transfered outside Eu/Eta (section 8). Heroku runs their servers in the US East region of AWS.

**Comment by naleksi** [comment]
You're correct, dear Sir! It was actually a task that should have been completed early in Spring and noticed again at the beginning of the FICORA audit. I'll hasten it to get it fixed the soonest. 

We never had intention to give wrong impressions. At first it we thought the server might end up being in EU. However, now the crucial part seems to be coming to EU, to a separate server. However, this needs to be fixed anyway. 

Thanks! :)

**Comment by betelgeuse** [comment]
@naleksi Engine Yard does provide hosting in the Europe Region. It can be a bit more expensive than Heroku and a little bit more effort but data would remain in Europe. I am not familiar enough with legislation to say if it still causes problems as both Amazon and Engine Yard are American countries. I know there's there are the safe harbor provisions so it might matter whether both comply to them.

**Comment by naleksi** [comment]
@betelgeuse Yes, Amazon is in Safe harbor, but Heroku is not, and although they have plans to put host also in Europe, they don't have anything at the moment. That is not, however, a big problem at the moment. There are two components in here. 1) the discussion forum which can easily continue to be hosted from US. The considerations are more practical, like is the roundtrip too slow latency wise, but that is not a problem at the moment. 2) the online signing of petitions, which we will be bringing to local soil soon now. Naturally we can reconsider this later on, but at the moment the priorities are to get the online signing launched the soonest. Later during the year we can also relocate the discussions if needed.

**Comment by betelgeuse** [comment]
What is the timetable here? It doesn't leave a good impression that the site still misleads people.

**Comment by naleksi** [comment]
@betelgeuse Hi! Thanks for the reminder! True, it should be fixed the soonest. I raised this issue to the other team responsible for TOS and other legalese. They are going to do a big revamp for all legalese, thus quick-fixing this was lost in a process. No excuse for it. I reraised it, and it will be fixed by Monday. 

By the way, the new TOS will be put under scrutiny in Avoin ministeriö FB group prolly next week, so join it if you want to take part of that discussion. (http://www.facebook.com/groups/Avoinministerio/)

**Comment by naleksi** [comment]
@betelgeuse for some odd reason I got the ticket closed before it's time. However, the last close is from commit that includes link to updated doc (https://dl.dropbox.com/u/15918701/henkilorekisteriseloste%203.9.2012.pdf). Please check that out! 

And also unfortunately the discussion on totally revamped doc is still pending, but please keep eye on FB group to participate on discussion when the other team releases the new doc. Thanks again!

**Comment by naleksi** [comment]
Oh, and it should be said it will take a while before this gets deployed to master due so many other changes...

**Comment by naleksi** [comment]
Finally, it's also in production. As said, this was just a semi-forced "quick" fix (which unfortunately took way too long). New version is in the works, so I hope we get to update that way quicker!

**Comment by betelgeuse** [comment]
@naleksi for small fixes it's always easy to use rebase or make the commit directly against the commit running in production and then merge it with the bigger pending changes. Generally the use of feature branches prevents bigger changes from holding up others. I think the doc still has a problem in that it states that information will not be given to third parties. IANAL but I think Amazon and Heroku are third parties. Thanks for finally looking at the issue.
